# Generated by Django 4.1.2 on 2022-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qalendiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='usuario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
