# Generated by Django 4.1.2 on 2022-11-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qalendiary', '0003_prueba_objetivo_fecha_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='fecha_obj',
            field=models.DateField(),
        ),
    ]
