# Generated by Django 4.1.2 on 2022-11-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qalendiary', '0006_alter_objetivo_fecha_alter_objetivo_fecha_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
