# Generated by Django 4.1.2 on 2022-11-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qalendiary', '0003_pruebita'),
        ('Qalendiary', '0007_alter_objetivo_fecha'),
    ]

    operations = [
    ]
