# Generated by Django 4.1.2 on 2022-11-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qalendiary', '0008_merge_0003_pruebita_0007_alter_objetivo_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pruebita',
        ),
    ]
